apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
  - port: 5432
  selector:
   app: postgres
