# This is a YAML-formatted file.
# Declare variables to be passed into helm templates.
microService:
  name: dts-dev-dev-nlp-governor
  namespace: dev-dev
  replicas: 1
  image: "concertohealthai/edgeserver:nlp-governor-dev-35-dts_ballad"
  memory: 4Gi
  cpu: 2
  max_memory: 4Gi
  max_cpu: 2
  port: 443
  healthcheckport: 30052
  nodeport: 30022
  acm: 	"arn:aws:acm:us-east-1:797970637915:certificate/46de82d7-d95f-43b6-a921-c92add23820d"
  sg: sg-0cd3587ff45624d5b
  EnvVariable:
    TARGET_POP_URL:      https://w6tazyqb1a.execute-api.us-east-1.amazonaws.com/dts_dev/rwe/
    PATIENT_MAPPER_URL:  https://p3ad4ocjyh.execute-api.us-east-1.amazonaws.com/edge/pm_dev
    NLP_PIPELINE_URL:    https://p3ad4ocjyh.execute-api.us-east-1.amazonaws.com/edge/nlp-pipeline
    ELASTICSEARCH_URL:   None
    S3_BUCKET:           emol-dev-edge-server
    SECRET_ID:           edge-dev