# This is a YAML-formatted file.
# Declare variables to be passed into helm templates.
microService:
  name: dts-patient-mapper
  namespace: default
  replicas: 1
  image: "concertohealthai/edgeserver:patient_mapper-5-prod"
  memory: 4Gi
  cpu: 2
  max_memory: 4Gi
  max_cpu: 2
  port: 443
  nodeport: 30009
  acm: 	"arn:aws:acm:us-east-1:797970637915:certificate/46de82d7-d95f-43b6-a921-c92add23820d"
  sg: sg-0cd3587ff45624d5b
  EnvVariable:
    GENOMIC_API_URL: 'https://genomics.api.emolhealth.com/v1'
    S3_BUCKET: dts-edge-server
    SECRET_ID: dts-edge-sm
    IS_TOKEN_ENCRYPTED: true
    EMOL_API_LIMIT: 500
    EMOL_API_PATIENT_LOOP: 3
    OWL_DB_VAULT_KEY: "owl_database"
